sector_etfs:
  - XLE   # Energy
  - XLB   # Materials
  - XLI   # Industrials
  - XLU   # Utilities
  - XLV   # Health Care
  - XLF   # Financials
  - XLY   # Consumer Discretionary
  - XLP   # Consumer Staples
  - XLK   # Technology
  - XLC   # Communication Services
  - XLRE  # Real Estate

synthetic_etfs:
  - XLRE
  - XLC

benchmark: SPY

sector_names:
  SPY: 'S&P 500 ETF'
  XLE: 'Energy Select Sector SPDR'
  XLB: 'Materials Select Sector SPDR'
  XLI: 'Industrials Select Sector SPDR'
  XLU: 'Utilities Select Sector SPDR'
  XLV: 'Health Care Select Sector SPDR'
  XLF: 'Financial Select Sector SPDR'
  XLY: 'Consumer Discretionary Select Sector SPDR'
  XLP: 'Consumer Staples Select Sector SPDR'
  XLK: 'Technology Select Sector SPDR'
  XLC: 'Communication Services Select Sector SPDR'
  XLRE: 'Real Estate Select Sector SPDR'  

sector_holdings:
  XLE:
    - XOM, CVX, COP, EOG, WMB, MPC, KMI, PSX, OKE, SLB, VLO, HES, BKR, TRGP, EQT, OXY, FANG, EXE, DVN, CTRA, TPL, HAL, APA
  XLB:
    - LIN, SHW, ECL, FCX, NEM, APD, NUE, MLM, VMC, CTVA, DD, IP, PPG, SW, AMCR, DOW, IFF, PKG, STLD, LYB, BALL, CF, AVY, MOS, EMN, ALB
  XLI:
    - GE, RTX, UBER, CAT, BA, GEV, HON, ETN, UNP, DE, ADP, LMT, TT, PH, TDG, MMM, WM, EMR, GD, HWM, CTAS, UPS, NOC, JCI, ITW, CSX, CARR, NSC, PWR, AXON, URI, FAST, FDX, PCAR, RSG, LHX, CMI, GWW
  XLU:
    - NEE, SO, CEG, DUK, VST, AEP, SRE, D, EXC, PEG, XEL, ETR, ED, WEC, NRG, PCG, DTE, AWK, PPL, AEE, ATO, ES, CNP, CMS, FE, EIX, NI, LNT, EVRG, PNW, AES
  XLV:
    - LLY, JNJ, ABBV, UNH, ABT, MRK, ISRG, TMO, AMGN, BSX, PFE, GILD, SYK, DHR, VRTX, MDT, BMY, MCK, CI, CVS, ELV, ZTS, HCA, REGN, COR, BDX, EW, IDXX, CAH, RMD, GEHC, DXCM, A, HUM, IQV, MTD, STE, LH
  XLF:
    - BRK.B, JPM, V, MA, BAC, WFC, GS, MS, AXP, C, SPGI, SCHW, BLK, PGR, COF, BX, MMC, ICE, CB, CME, KKR, FI, COIN, AJG, MCO, AON, PNC, USB, PYPL, BK, APO, TFC, TRV, ALL, AMP, AFL, AIG, MSCI, MET, FIS, NDAQ, PRU
  XLY:
    - AMZN, TSLA, HD, BKNG, MCD, TJX, LOW, SBUX, RCL, NKE, DASH, ORLY, CMG, HLT, MAR, AZO, ABNB, GM, F, ROST, YUM, EBAY, DHI, GRMN, CCL, TSCO, LEN, LULU, DRI, PHM, EXPE, ULTA, NVR, TPR, WSM, GPC, LVS, DPZ, APTV, DECK, BBY
  XLP:
    - COST, WMT, PG, PM, KO, PEP, MDLZ, MO, CL, TGT, KDP, KR, KMB, MNST, KVUE, SYY, GIS, ADM, STZ, DG, HSY, CHD, KHC, K, DLTR, EL, MKC, CLX, TSN, SJM, BG, CAG, HRL, TAP, WBA, LW, CPB, BF.B
  XLK:
    - NVDA, MSFT, AAPL, AVGO, ORCL, PLTR, CSCO, IBM, AMD, CRM, INTU, NOW, TXN, ACN, QCOM, AMAT, ADBE, MU, LRCX, PANW, KLAC, APH, ADI, CRWD, ANET, INTC, SNPS, CDNS, MSI, FTNT, ADSK, ROP, NXPI, TEL, WDAY, GLW, MCHP, DELL, FICO, CTSH, MPWR, ANSS, STX, IT, KEYS, SMCI, HPE, DDOG
  XLC:
    - META, GOOGL, NFLX, GOOG, TTWO, EA, DIS, CMCSA, TMUS, CHTR, T, VZ, WBD, LYV, OMC, FOXA, TKO, NWSA, IPG, MTCH, PARA, FOX, NWS
  XLRE:
    - AMT, PLD, WELL, EQIX, DLR, O, SPG, PSA, CCI, CBRE, CSGP, VICI, EXR, VTR, IRM, AVB, SBAC, EQR, WY, INVH, ESS, MAA, KIM, DOC, UDR, CPT, ARE, HST, REG, BXP, FRT